# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\banhb\Documents\Projects\2023\simple-store\ui\add_p2invoice_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_p2Invoice(object):
    def setupUi(self, p2Invoice):
        p2Invoice.setObjectName("p2Invoice")
        p2Invoice.resize(527, 193)
        self.gridLayout = QtWidgets.QGridLayout(p2Invoice)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(p2Invoice)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.p_name_input = QtWidgets.QLineEdit(p2Invoice)
        self.p_name_input.setObjectName("p_name_input")
        self.gridLayout.addWidget(self.p_name_input, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(p2Invoice)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.p_quantity_input = QtWidgets.QSpinBox(p2Invoice)
        self.p_quantity_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.p_quantity_input.setMinimum(1)
        self.p_quantity_input.setObjectName("p_quantity_input")
        self.gridLayout.addWidget(self.p_quantity_input, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(p2Invoice)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.unit_price_input = QtWidgets.QLineEdit(p2Invoice)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unit_price_input.setFont(font)
        self.unit_price_input.setReadOnly(True)
        self.unit_price_input.setObjectName("unit_price_input")
        self.gridLayout.addWidget(self.unit_price_input, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(p2Invoice)
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.create_date = QtWidgets.QDateTimeEdit(p2Invoice)
        self.create_date.setCalendarPopup(True)
        self.create_date.setObjectName("create_date")
        self.gridLayout.addWidget(self.create_date, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(p2Invoice)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.new_unit_price_input = QtWidgets.QLineEdit(p2Invoice)
        self.new_unit_price_input.setObjectName("new_unit_price_input")
        self.gridLayout.addWidget(self.new_unit_price_input, 4, 1, 1, 1)
        self.new_unit_price_warning = QtWidgets.QLabel(p2Invoice)
        self.new_unit_price_warning.setText("")
        self.new_unit_price_warning.setTextFormat(QtCore.Qt.MarkdownText)
        self.new_unit_price_warning.setObjectName("new_unit_price_warning")
        self.gridLayout.addWidget(self.new_unit_price_warning, 5, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(p2Invoice)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 2, 5, 1)

        self.retranslateUi(p2Invoice)
        self.buttonBox.accepted.connect(p2Invoice.accept) # type: ignore
        self.buttonBox.rejected.connect(p2Invoice.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(p2Invoice)

    def retranslateUi(self, p2Invoice):
        _translate = QtCore.QCoreApplication.translate
        p2Invoice.setWindowTitle(_translate("p2Invoice", "Thêm sản phẩm vào hóa đơn"))
        self.label.setText(_translate("p2Invoice", "**Tên sản phẩm**"))
        self.label_2.setText(_translate("p2Invoice", "**Số lượng**"))
        self.label_3.setText(_translate("p2Invoice", "**Đơn giá (VND)**"))
        self.label_5.setText(_translate("p2Invoice", "**Ngày mua**"))
        self.create_date.setDisplayFormat(_translate("p2Invoice", "d-M-yyyy hh:mm:ss"))
        self.label_4.setText(_translate("p2Invoice", "**Giá mới (nếu có)**"))
