# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\banhb\Documents\Projects\2023\NamKhangStore\ui\add_cus_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCus(object):
    def setupUi(self, AddCus):
        AddCus.setObjectName("AddCus")
        AddCus.resize(400, 105)
        self.gridLayout = QtWidgets.QGridLayout(AddCus)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(AddCus)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(AddCus)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cus_name_input = QtWidgets.QLineEdit(AddCus)
        self.cus_name_input.setObjectName("cus_name_input")
        self.gridLayout.addWidget(self.cus_name_input, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.cus_input_warning = QtWidgets.QLabel(AddCus)
        self.cus_input_warning.setText("")
        self.cus_input_warning.setTextFormat(QtCore.Qt.MarkdownText)
        self.cus_input_warning.setObjectName("cus_input_warning")
        self.gridLayout.addWidget(self.cus_input_warning, 1, 1, 1, 1)

        self.retranslateUi(AddCus)
        self.buttonBox.accepted.connect(AddCus.accept) # type: ignore
        self.buttonBox.rejected.connect(AddCus.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddCus)

    def retranslateUi(self, AddCus):
        _translate = QtCore.QCoreApplication.translate
        AddCus.setWindowTitle(_translate("AddCus", "Thêm khách hàng"))
        self.label.setText(_translate("AddCus", "Tên khách hàng"))
