# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\banhb\Documents\Projects\2023\NamKhangStore\ui\add_p2invoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_p2Invoice(object):
    def setupUi(self, p2Invoice):
        p2Invoice.setObjectName("p2Invoice")
        p2Invoice.resize(535, 204)
        self.formLayout = QtWidgets.QFormLayout(p2Invoice)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(p2Invoice)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(p2Invoice)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(p2Invoice)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(p2Invoice)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_3 = QtWidgets.QLabel(p2Invoice)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.unit_price_input = QtWidgets.QLineEdit(p2Invoice)
        self.unit_price_input.setObjectName("unit_price_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.unit_price_input)
        self.label_4 = QtWidgets.QLabel(p2Invoice)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.new_unit_price_input = QtWidgets.QLineEdit(p2Invoice)
        self.new_unit_price_input.setObjectName("new_unit_price_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.new_unit_price_input)
        self.buttonBox = QtWidgets.QDialogButtonBox(p2Invoice)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.new_unit_price_warning = QtWidgets.QLabel(p2Invoice)
        self.new_unit_price_warning.setText("")
        self.new_unit_price_warning.setTextFormat(QtCore.Qt.MarkdownText)
        self.new_unit_price_warning.setObjectName("new_unit_price_warning")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.new_unit_price_warning)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.retranslateUi(p2Invoice)
        self.buttonBox.accepted.connect(p2Invoice.accept) # type: ignore
        self.buttonBox.rejected.connect(p2Invoice.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(p2Invoice)

    def retranslateUi(self, p2Invoice):
        _translate = QtCore.QCoreApplication.translate
        p2Invoice.setWindowTitle(_translate("p2Invoice", "Thêm thông tin sản phẩm vào hóa đơn"))
        self.label.setText(_translate("p2Invoice", "**Tên sản phẩm**"))
        self.label_2.setText(_translate("p2Invoice", "**Số lượng**"))
        self.label_3.setText(_translate("p2Invoice", "**Đơn giá**"))
        self.label_4.setText(_translate("p2Invoice", "**Giá mới (nếu có)**"))
