# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\banhb\Documents\Projects\2023\simple-store\ui\add_p_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProduct(object):
    def setupUi(self, AddProduct):
        AddProduct.setObjectName("AddProduct")
        AddProduct.resize(537, 194)
        self.gridLayout = QtWidgets.QGridLayout(AddProduct)
        self.gridLayout.setObjectName("gridLayout")
        self.unit_price_input = QtWidgets.QLineEdit(AddProduct)
        self.unit_price_input.setObjectName("unit_price_input")
        self.gridLayout.addWidget(self.unit_price_input, 2, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddProduct)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(AddProduct)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(AddProduct)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.p_name_input = QtWidgets.QLineEdit(AddProduct)
        self.p_name_input.setObjectName("p_name_input")
        self.gridLayout.addWidget(self.p_name_input, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(AddProduct)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(AddProduct)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.seperate_unit_price = QtWidgets.QLabel(AddProduct)
        self.seperate_unit_price.setText("")
        self.seperate_unit_price.setTextFormat(QtCore.Qt.MarkdownText)
        self.seperate_unit_price.setObjectName("seperate_unit_price")
        self.gridLayout.addWidget(self.seperate_unit_price, 3, 1, 1, 2)
        self.unit_price_warnin_input = QtWidgets.QLabel(AddProduct)
        self.unit_price_warnin_input.setTextFormat(QtCore.Qt.MarkdownText)
        self.unit_price_warnin_input.setObjectName("unit_price_warnin_input")
        self.gridLayout.addWidget(self.unit_price_warnin_input, 5, 1, 1, 1)

        self.retranslateUi(AddProduct)
        self.buttonBox.accepted.connect(AddProduct.accept) # type: ignore
        self.buttonBox.rejected.connect(AddProduct.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddProduct)
        AddProduct.setTabOrder(self.p_name_input, self.unit_price_input)
        AddProduct.setTabOrder(self.unit_price_input, self.comboBox)

    def retranslateUi(self, AddProduct):
        _translate = QtCore.QCoreApplication.translate
        AddProduct.setWindowTitle(_translate("AddProduct", "Thêm sản phẩm"))
        self.label_2.setText(_translate("AddProduct", "**Giá tiền (VND)**"))
        self.label_3.setText(_translate("AddProduct", "**Vị trí trong kho**"))
        self.label.setText(_translate("AddProduct", "**Tên sản phẩm**"))
        self.unit_price_warnin_input.setText(_translate("AddProduct", "Warning"))
